# todo: 需根据实际redis服务配置更改
IP = "127.0.0.0"
PORT = 8787
Password = ""
DB = 0
max_retries = 0
pool_size = 32
read_timeout = 3
write_timeout = 3
idle_timeout = 300
idle_check_frequency = 60
max_conn_age = 300
pool_timeout = 8